---
title: "conditional_loops"
format: html
editor: visual
execute:
  warning: TRUE
---

```{r}
library(tidyverse)
```

```{r}
#TASK 1
#Create an object w a value of 48

pm2_5 <- 20

if(pm2_5 < 100) {
  print("Low to moderate risk")
} else if (pm2_5 < 150 & pm2_5 >= 100) {
  print("unhealthy for sensitive groups")
  } else if (pm2_5 >= 150) {
    print("health risk present")
  }

```

```{r}
#Task 2
species <- "blue whale"

if(str_detect(species, "whale")) {
  print("You found a whale!")
}
```

```{r}
#Task 3
base_burrito = 6.5

main_ingredient = "steak"

switch(main_ingredient,
       "veggie" = print(base_burrito),
       "chicken" = print(base_burrito + 3),
       "steak" = print(base_burrito + 3.25))

```

```{r}
#Task 4 write a for loop that iterates through fish & returns what proportion of total fish in the tank that are that species
fish <- c(8, 10, 12, 23)

species <- c("goldfish", "tetras", "guppies","mollies")

for(i in seq_along(fish)) {
  prop_fish <- fish[i]/sum(fish)
  print(prop_fish)}

```

```{r}

for(i in seq_along(month.name)) {
  find <- (paste(month.name[i], "is month", i))
  print(find)
}
```
